language: generic

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
    - EMACS_VERSION="24.5 25.3 26.1 26.2 master"

addons:
  homebrew:
    packages:
      - libxml2                 # fix notfound libxml/tree.h issue
      - texinfo                 # Emacs-27's info required latext texinfo

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

jobs:
  include:
    - stage: "Mac build (Mojave)"
      os: osx
      osx_image: xcode10.2
      env:
        global:
          - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
        matrix:
          - EMACS_VERSION="24.5"
          - EMACS_VERSION="25.3"
          - EMACS_VERSION="26.1"
          - EMACS_VERSION="26.2"
          - EMACS_VERSION="master"
      install:
        - uname -a
        - sw_vers
        - make
      script:
        - make push
