language: generic

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
    - EMACS_VERSION="23.4 24.5 25.3 26.1 26.2 master"

addons:
  homebrew:
    packages:
      - libxml2

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

jobs:
  include:
    - stage: "Mac build"
      os: osx
      osx_image: xcode10.2
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
      install:
        - uname -a
        - sw_vers
        - make -j
      script:
        - make push -j
