language: generic

cache:
  directories:
    - /tmp/emacs

env:
  matrix:
#     - EMACS_VERSION=23.4
#     - EMACS_VERSION=24.5
#     - EMACS_VERSION=25.3
#     - EMACS_VERSION=26.1
    - EMACS_VERSION=master

install:
  - pwd

script:
  - make  
