language: generic
dist: precise

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
    - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"

addons:
  homebrew:
    packages:
      - libxml2                 # fix issue; not found libxml/tree.h
      - texinfo                 # Emacs-27's info required latext texinfo
  apt:
    packages:
      - texinfo

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

jobs:
  include:
    - &mojave-build
      stage: "mojave build"
      os: osx
      osx_image: xcode10.2
      env: EMACS_VERSION="24.5"
      install: make
      script: make push
    - <<: *mojave-build
      env: EMACS_VERSION="25.3"
    - <<: *mojave-build
      env: EMACS_VERSION="26.1"
    - <<: *mojave-build
      env: EMACS_VERSION="26.2"
    - <<: *mojave-build
      env:
        allow_failures:
          - EMACS_VERSION="master"
