language: generic

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
  matrix:
    - EMACS_VERSION=26.2
#     - EMACS_VERSION=23.4
#     - EMACS_VERSION=24.5
#     - EMACS_VERSION=25.3
#     - EMACS_VERSION=26.1
#     - EMACS_VERSION=master

addons:
  homebrew:
    packages:
      - libxml2

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

jobs:
  include:
    - stage: "macOS"
      os: osx
      osx_image: xcode10.2
      env:
        - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
      install:
        - uname -a
        - sw_vers
        - make -j
      script:
        - make push -j
        - ls -la .dist
        - ls -la .dist/emacs-26.2
