language: generic

os: osx
osx_image: xcode10.2            # macOSX Mojave

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
    - EMACS_VERSION="master"

addons:
  homebrew:
    packages:
      - texinfo                 # Emacs-27's info required latext texinfo

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

install:
  # fix issue; not found libxml/tree.h
  # see https://github.com/caldwell/build-emacs#xcode-command-line-tools
  - sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
  - make

script:
  - make push
