language: generic

cache:
  directories:
    - /tmp/emacs

env:
  matrix:
#     - EMACS_VERSION=23.4
#     - EMACS_VERSION=24.5
#     - EMACS_VERSION=25.3
#     - EMACS_VERSION=26.1
    - EMACS_VERSION=master

install:
  - pwd
  - mkdir -p /tmp/.ssh
  - ls -la /tmp/.ssh
  - openssl aes-256-cbc -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv -in .travis_rsa.enc -out /tmp/.ssh/rsync-files-conao3_rsa -d
  - ls -la /tmp/.ssh
  - chmod 600 /tmp/.ssh/rsync-files-conao3_rsa
  - ls -la /tmp/.ssh

script:
  - make
  - rsync -av -e "ssh -v -i /tmp/.ssh/rsync-files-conao3_rsa -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null'" ../emacs-builder conao3@files.conao3.com:~/www/files
