language: generic

cache:
  directories:
    - ~/.work/emacs

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
  matrix:
#     - EMACS_VERSION=23.4
#     - EMACS_VERSION=24.5
#     - EMACS_VERSION=25.3
#     - EMACS_VERSION=26.1
    - EMACS_VERSION=master

install:
  - pwd
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv -in .travis_rsa.enc -out ~/.ssh/rsync-files-conao3_rsa -d
  - chmod 600 ~/.ssh/rsync-files-conao3_rsa

jobs:
  include:
    - stage: "macOS"
      os: osx
      osx_image: xcode10.2
      script:
        - uname -a
        - sw_vers
        - ls -la ~/../
        - ls -la ~/
        - make
