language: generic

cache:
  directories:
    - /tmp/emacs

env:
  matrix:
#     - EMACS_VERSION=23.4
#     - EMACS_VERSION=24.5
#     - EMACS_VERSION=25.3
#     - EMACS_VERSION=26.1
    - EMACS_VERSION=master

install:
  - pwd
  - openssl aes-256-cbc -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv -in .travis_rsa.enc -out ~/.ssh/rsync-files.conao3.com_rsa -d
  - chmod 600 ~/.ssh/id_rsa

script:
  - make
  - rsync -av -e "ssh -v -i ~/.ssh/rsync-files.conao3.com_rsa" ../emacs-builder conao3@files.conao3.com:~/www/files
