language: generic

env:
  global:
    - SSHKEY=~/.ssh/rsync-files-conao3_rsa
    - PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
  matrix:
    - EMACS_VERSION="24.5"
    - EMACS_VERSION="25.3"
    - EMACS_VERSION="26.1"
    - EMACS_VERSION="26.2"
    allow_failures:
      - EMACS_VERSION="master"

matrix:
  include:
    - os: osx
      osx_image: xcode10.2      # Mojave
    - os: osx
      osx_image: xcode10.1      # High sierra

addons:
  homebrew:
    packages:
      - libxml2                 # fix issue; not found libxml/tree.h
      - texinfo                 # Emacs-27's info required latext texinfo
  apt:
    packages:
      - texinfo

before_install:
  - pwd
  - openssl aes-256-cbc
      -K $encrypted_6932eec903aa_key -iv $encrypted_6932eec903aa_iv
      -in .travis_rsa.enc -out $SSHKEY -d
  - chmod 600 $SSHKEY

install:
  - make

# script:
#   - make push

after_success:
  - make rsync
